version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - gosec
    - unconvert
    - unparam
    - prealloc

formatters:
  enable:
    - gofmt
    - goimports

linters-settings:
  errcheck:
    check-type-assertions: true
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gosec:
    excludes:
      - G101
  misspell:
    locale: US

formatters-settings:
  goimports:
    local-prefixes:
      - github.com/Glider2355/ddl-lock-analyzer

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - gosec
        - unparam
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  formats:
    colored-line-number: {}
  sort-results: true
