version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - gosec
    - unconvert
    - unparam
    - prealloc

  settings:
    errcheck:
      check-type-assertions: true
    govet:
      enable-all: true
      disable:
        - fieldalignment
    gosec:
      excludes:
        - G101
    misspell:
      locale: US

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - gosec
          - unparam

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    goimports:
      local-prefixes:
        - github.com/Glider2355/ddl-lock-analyzer

output:
  formats:
    text:
      path: stdout
      colors: true
